import Head from "next/head";
import { About, HomePage, Team, Projects, Blog, Contact } from "../containers";
import { client } from "../client";
import { groq } from "next-sanity";
import { Footer } from "../components";

// build the query to fetch data
const getAbout = groq`*[_type == "about"]`;
const getTeam = groq`*[_type == "team"]`;
const getProjects = groq`*[_type == "projects"]`;

export default function Home({ about, team, projects }) {
  return (
    <>
      <Head>
        <title>Codingrah</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <HomePage />
        <About about={about} />
        <Team team={team} />
        <Projects projects={projects} />
        <Blog />
        <Contact />
        <Footer />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const about = await client.fetch(getAbout);
  const team = await client.fetch(getTeam);
  const projects = await client.fetch(getProjects);
  return {
    props: {
      about,
      team,
      projects,
    },
  };
}
